version: '3.1'

services:

  mongo:
    image: mongo:4.4.17
    restart: "no"
    volumes:
      - ../data/mongodb:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dev
      MONGO_INITDB_DATABASE: movil_parcial

  mongo-script:
    image: mongo:4.4.17
    restart: "no"
    volumes:
      - ./data:/data/
      - ./import-mongo.sh:/import-mongo.sh
    environment:
      MONGO_HOST: mongo
      MONGO_USER: root
      MONGO_PASS: dev
    depends_on:
      - "mongo"
    command: sh /import-mongo.sh
